CREATE TABLE OUTCOMES (
    ship varchar(30),
    battle varchar(30),
    result varchar(10)
);

insert into OUTCOMES values ('Arizona', 'Pearl Harbor', 'sunk');
insert into OUTCOMES values ('Bismarck', 'Denmark Strait', 'sunk');
insert into OUTCOMES values ('California', 'Surigao Strait', 'ok');
insert into OUTCOMES values ('Duke of York', 'North Cape', 'ok');
insert into OUTCOMES values ('Fuso', 'Surigao Strait', 'sunk');
insert into OUTCOMES values ('Hood', 'Denmark Strait', 'sunk');
insert into OUTCOMES values ('King George V', 'Denmark Strait', 'ok');
insert into OUTCOMES values ('Kirishima', 'Guadalcanal', 'sunk');
insert into OUTCOMES values ('Prince of Wales', 'Denmark Strait', 'damaged');
insert into OUTCOMES values ('Rodney', 'Denmark Strait', 'ok');
insert into OUTCOMES values ('Schamhorst', 'North Cape', 'sunk');
insert into OUTCOMES values ('South Dakota', 'Guadalcanal', 'damaged');
insert into OUTCOMES values ('Tennessee', 'Surigao Strait', 'ok');
insert into OUTCOMES values ('Washington', 'Guadalcanal', 'ok');
insert into OUTCOMES values ('West Virginia', 'Surigao Strait', 'ok');
insert into OUTCOMES values ('Yamashiro', 'Surigao Strait', 'sunk');
